### ISSUE TITLE
Clicking "open this link to login" doesn't work

### ISSUE THREAD

**Issue by dhry** [stravo1/obsidian-gdrive-sync#15]
Steps to reproduce
- Install plugin
- Find plugin in Settings → Community plugins → Google drive sync
- Click "Open this link to login"

Result
- Obsidian shuts down completely
- No additional browser window opens

Expected result
- Google login page should appear, providing a token to use

**Comment by stravo1** [comment]
huh, that's weird. what device are you using? mobile or desktop? and what OS? can you check on other devices if the issue persists?

**Comment by dhry** [comment]
Using Windows 10 professional, desktop Obsidian v1.5.12 (installer version 1.5.3). I already uninstalled it in preparation for new version. I only have a cellphone to test it on, can do that this weekend.

**Comment by stravo1** [comment]
i have tested the plug-in on Linux, macOS and Android and have not been able to replicate the issue. i haven't tested on windows. you can test it on your phone, i can test it on windows this weekend :)

**Comment by stravo1** [comment]
i tested the latest release (v0.9.9-beta-7-5) on Windows 11 and the link works, it opens a browser window.
