### ISSUE TITLE
iOS broken

### ISSUE THREAD

**Issue by jet082** [stravo1/obsidian-gdrive-sync#16]
Unfortunately, it seems that iOS is broken. I set up the plugin on desktop on a completely blank project, then copied over the folder to iOS and opened it on Obsidian. The syncing works on Desktop just fine. I am using v0.9.9-beta-7-2.

The following errors occurred:

# verbose-log-gdrive-plugin

```
LOG: received accessToken

LOG: getting vault id

LOG: Exited writeToErrorLogFile

LOG: Entering completeAllPendingSyncs

LOG: Entering getLatestContent

LOG: Exited getLatestContent

LOG: Exiting refreshFilesListInDriveAndStoreInSettings

LOG: Exited writeToErrorLogFile

LOG: Exited writeToErrorLogFile

LOG: Exited checkForConnectivity

LOG: Exited checkForConnectivity

LOG: Entering writeToErrorLogFile

LOG: Exited checkForConnectivity

LOG: Exited writeToErrorLogFile

LOG: Exiting refreshFilesListInDriveAndStoreInSettings

LOG: Exiting refreshFilesListInDriveAndStoreInSettings

LOG: Exited writeToErrorLogFile

LOG: Entering writeToErrorLogFile

LOG: Too many errors within a minute. Halting all operations.
```

# error-log-gdrive-plugin
```
Wed Apr 24 2024 02:27:54 GMT-0500 (Central Time)-Error-ERROR: Unable to complete action: - getFilesList => Error - Request failed, status 400 - t@capacitor://localhost/app.js:1:1977943
GG@capacitor://localhost/app.js:1:1978137
@capacitor://localhost/app.js:1:1978701
@capacitor://localhost/app.js:1:237060
a@capacitor://localhost/app.js:1:235883-newError@
@

Wed Apr 24 2024 02:27:54 GMT-0500 (Central Time)-Error-ERROR: Unable to complete action: - getFilesList => Error - Request failed, status 400 - t@capacitor://localhost/app.js:1:1977943
GG@capacitor://localhost/app.js:1:1978137
@capacitor://localhost/app.js:1:1978701
@capacitor://localhost/app.js:1:237060
a@capacitor://localhost/app.js:1:235883-newError@
@

Wed Apr 24 2024 02:27:54 GMT-0500 (Central Time)-Error-ERROR: Unable to complete action: - getFilesList => Error - Request failed, status 400 - t@capacitor://localhost/app.js:1:1977943
GG@capacitor://localhost/app.js:1:1978137
@capacitor://localhost/app.js:1:1978701
@capacitor://localhost/app.js:1:237060
a@capacitor://localhost/app.js:1:235883-newError@
@

Wed Apr 24 2024 02:27:54 GMT-0500 (Central Time)-Error-ERROR: Unable to complete action: - getFilesList => Error - Request failed, status 400 - t@capacitor://localhost/app.js:1:1977943
GG@capacitor://localhost/app.js:1:1978137
@capacitor://localhost/app.js:1:1978701
@capacitor://localhost/app.js:1:237060
a@capacitor://localhost/app.js:1:235883-newError@
@

Wed Apr 24 2024 02:27:55 GMT-0500 (Central Time)-Error-ERROR: Unable to complete action: - getFilesList => Error - Request failed, status 400 - t@capacitor://localhost/app.js:1:1977943
GG@capacitor://localhost/app.js:1:1978137
@capacitor://localhost/app.js:1:1978701
@capacitor://localhost/app.js:1:237060
a@capacitor://localhost/app.js:1:235883-newError@
@

Wed Apr 24 2024 02:27:55 GMT-0500 (Central Time)-Error-ERROR: Unable to complete action: - getFilesList => Error - Request failed, status 400 - t@capacitor://localhost/app.js:1:1977943
GG@capacitor://localhost/app.js:1:1978137
@capacitor://localhost/app.js:1:1978701
@capacitor://localhost/app.js:1:237060
a@capacitor://localhost/app.js:1:235883-newError@
@

Wed Apr 24 2024 02:27:56 GMT-0500 (Central Time)-Error-FATAL ERROR: Too many errors within a minute.-@
@
```

**Comment by stravo1** [comment]
i am aware of this issue, but till now haven't figured out how to fix it, will take another look 

https://github.com/stravo1/obsidian-gdrive-sync/issues/1#issuecomment-1878468290

**Comment by louux** [comment]
Hey Stravos. Not sure if this helps any but I am updated with v0.9.9-beta-7-4 and I also get an error using iOS.

Desktop working fine. I copy folder onto iOS from Desktop. 

Worth mentioning, my desktop Obsidian vault is reading from Google Drive and my iOS vault is reading from iCloud. 

Attached are the logs. 
[error-log-gdrive-plugin.md](https://github.com/stravo1/obsidian-gdrive-sync/files/15170620/error-log-gdrive-plugin.md)
[verbose-log-gdrive-plugin.md](https://github.com/stravo1/obsidian-gdrive-sync/files/15170621/verbose-log-gdrive-plugin.md)

**Comment by louux** [comment]
Hey, Stravo

Main vault is in Documents on my Macbook and I move the Vault folder to my iPhone via Airdrop. It creates a new Obsidian Folder in iCloud with my Vauilt folder within it. Here are the logs with errors. 

[error-log-gdrive-plugin.md](https://github.com/stravo1/obsidian-gdrive-sync/files/15199411/error-log-gdrive-plugin.md)
[verbose-log-gdrive-plugin.md](https://github.com/stravo1/obsidian-gdrive-sync/files/15199412/verbose-log-gdrive-plugin.md)

**Comment by awei55** [comment]
Hi! Same issue between iOS and Windows 11. Sync fails on iOS, works perfectly fine on desktop. The vault was copied as per instructions into the Obsidian app folder through iTunes, and the vault is accessible and editable on phone, as well as the plugin. 
Logs attached!

using v0.9.9-beta-8

[error-log-gdrive-plugin.md](https://github.com/stravo1/obsidian-gdrive-sync/files/15281889/error-log-gdrive-plugin.md)
[verbose-log-gdrive-plugin.md](https://github.com/stravo1/obsidian-gdrive-sync/files/15281890/verbose-log-gdrive-plugin.md)

**Comment by stravo1** [comment]
it's very hard for me to debug this issue as i don't own an iPhone :')

and going back and forth via "test" releases on GitHub is very inefficient, so until i can get hold of an iOS device or someone is willing to do the testing for me remotely, i am not sure how to debug this wierd issue.

so i created a discord channel for testing, please do join and help me debug this issue :)

https://discord.com/invite/uThNmUXA

**Comment by aglasson** [comment]
Just adding to this:
I'm finding the same issue both v0.9.9-beta-7-5 & v0.9.9-beta-8.
Both work find on Windows but as soon as the iOS app interacts with the directory manually moved to iOS files it throws the following errors in UI.
![image](https://github.com/stravo1/obsidian-gdrive-sync/assets/11340849/02401f7f-15f0-47a1-912f-964fd6bce395)

**Comment by stravo1** [comment]
fixed at https://github.com/stravo1/obsidian-gdrive-sync/releases/tag/v0.9.9-beta-9
