### ISSUE TITLE
same folder across pc and android 

### ISSUE THREAD

**Issue by fabertel** [stravo1/obsidian-gdrive-sync#17]
thanks for building up this app ! 
I'm trying to sync my android phone and desktop on the same Google Drive .. But whenever I install your plug in and initialize it , a NEW Google Drive folder is created so I end up with two separate folders : one from the computer and a different one from the phone .. how can i make one ?

and , where do i config the refresh rythm ? 

thanks! 
 Fabio

**Comment by stravo1** [comment]
hello Fabio!
when you initialise the plug-in it creates it own folder named "obsidian" in Drive and stores all your vaults under that folder (say for eg: "obsidian/my-vault-1"), so any folder which you might have created yourself or using other plug-ins in Drive won't be compatible.

to sync across devices you need to create a vault with the same name on the both the devices and initialise the plug-in. If you have synced the vault on one device then the files will be automatically downloaded in the other device.

so the steps, would be:
1. Create a new vault, say with the name "vault-1", install the plug-in on that vault.
OR
1. You can install the plug-in in an existing vault (please make sure to keep a back-up)
2. Provide the refresh token.
3. Initialise the vault folder, here the plug-in creates a subfolder with the same name as your vault under the "obsidian", and also upload all the existing files in the vault to drive.

![Screenshot_20240430-124617.png](https://github.com/stravo1/obsidian-gdrive-sync/assets/76593476/629a3a39-5a8d-48d8-8a72-5adfdd3c26b8)

![Screenshot_20240430-124439.png](https://github.com/stravo1/obsidian-gdrive-sync/assets/76593476/f4b73624-ae3c-448d-9d70-51936523cd32)

4. Reload the plug-in
5. On the other device (say your PC), create the vault with the same name ("vault-1") and simply install the plug-in and login. It will start syncing automatically.

And there is a separate settings menu for the plug-in in the settings menu, under Community Plugins:
![Screenshot_20240430-124936.png](https://github.com/stravo1/obsidian-gdrive-sync/assets/76593476/ac6ab9ea-a0ce-4a70-9305-895066ae9c3b)

**Comment by fabertel** [comment]
Thanks Sayantan
ive followed you step by step but getting different results .

   - i keep getting 2 folders even if name is the same and they are not
   created under obsidian
   - I dont understand how to activate the recurrent backup or control
   the refresh speed . i can only do one backup when initializing the
   backup , have to do that manually and any time a  new folder is created


thanks!!
Fabio

**Comment by stravo1** [comment]
i introduced a bug in the previous build while trying to test for iOS compatibility, sorry for the inconvenience, can you try the latest build, i would suggest you to delete all the previously uploaded folders in Drive and start fresh.

https://github.com/stravo1/obsidian-gdrive-sync/releases/v0.9.9-beta-7-5

**Comment by GottliebGlob** [comment]
The issue on android is still here. Files are uploaded to gdrive but pluging says that vaults is not initialized after reload. Heres the log: 

`

LOG: received accessToken

LOG: rootFolder available

LOG: getting vault id

LOG: vault not found

LOG: adding settings UI`

**Comment by GottliebGlob** [comment]
<img width="330" alt="Снимок экрана 2024-05-02 в 18 39 49" src="https://github.com/stravo1/obsidian-gdrive-sync/assets/53971863/11c8d7ce-ae09-4d43-a75b-8115d0b09383">

**Comment by stravo1** [comment]
you've uncovered a really nasty and clever bug and the only reason i could figure it out was because you uploaded the last screenshot.

it's the name of the vault, if you use any other name other than "obsidian" for your vault it should work fine.

i'm working on the fix asap.

thnx :)

**Comment by stravo1** [comment]
also you need to delete the folder named obsidian which is inside the root obsidian folder in your Drive, it's the clash between these two folders which is causing the issue.

**Comment by GottliebGlob** [comment]
Ok I'll try today. You did a great job mate, gl to you

**Comment by stravo1** [comment]
fixed both issues at 0.9.9-beta-9 and 0.9.9-beta-10
