### ISSUE TITLE
how could i access the google-drive-sync-enabled-vault on my ipad?

### ISSUE THREAD

**Issue by mdc-2468** [stravo1/obsidian-gdrive-sync#25]
I have set up the whole google sync plugin on my laptop, but how could i access the vault and sync on my ipad?
I have already created a new vault having the same name as the vault on my drive.
I tried to copy the files from the google drive of the vault to my local ipad storage, I saw 4 files show up on the Obsidian iOS app, but when I clicked 'Files', there is no files show up.

**Comment by stravo1** [comment]
have you managed to install the plug-in on the iPad? like can you access the plug-in menu from the iPad?

**Comment by mdc-2468** [comment]
I tried to browse community plug in on ipad, however I couldn't find any plugins named anything like gdrive-sync.

**Comment by stravo1** [comment]
this probably means you don't have the plug-in installed on the iPad. try copying the entire vault from the desktop (along with the ```.obsidian``` folder).

if you face any issues join the discord server, there are other ppl with iOS devices who can help you out:

https://discord.com/invite/dPasX4Ac2P

**Comment by mdc-2468** [comment]
it works now after copy the `.obsidian` obsidian folder thanks!
