### ISSUE TITLE
[Feature Request] Blacklist Files/Folders from Uploads

### ISSUE THREAD

**Issue by woliver99** [stravo1/obsidian-gdrive-sync#31]
It would be nice if I was able to blacklist folders from uploads so I could use a tool like [Obsidian Shell](https://github.com/Chaoses-Ib/ObsidianShell).

Obsidian Shell allows me to open arbitrary markdown files outside of a vault. It works by making a folder, copying the contents of the folder and then deleting it after but I don't want it to upload to Google Drive because it causes problems with it and even has caused it to delete straight up folders outside of Obsidian.

**Comment by stravo1** [comment]
i did not know that plug-ins can delete files out of the vault in which they were installed, that's something new!

and yeah i agree, a blocklist would be nice

thanks for the suggestions, will take a look very soon :))

**Comment by stravo1** [comment]
done ✅
https://github.com/stravo1/obsidian-gdrive-sync/releases/tag/v0.9.9-beta-12
