### ISSUE TITLE
Daily Note pages are deleted immediately after creation

### ISSUE THREAD

**Issue by torbendury** [stravo1/obsidian-gdrive-sync#36]
Hello, and first of all thank you very much for maintaining this plugin.

I recently started using Obsidian and went on using your plugin for GDrive synchronization. I configured the "Daily Notes" core plugin, however the pages created by it (also on-demand by "Open today's daily note") are immediately being deleted before I can write anything.

This might be related to https://github.com/stravo1/obsidian-gdrive-sync/issues/30, I will try the workaround of disabling automatic sync for this folder. However I thought it might be good to know that this feature also seems to be affected.

**Comment by stravo1** [comment]
https://github.com/stravo1/obsidian-gdrive-sync?tab=readme-ov-file#q-notes-created-from-templates-get-deleted-automatically-how-to-solve-it
