### ISSUE TITLE
Discord link not working/How does this fair against Obsidian Sync?

### ISSUE THREAD

**Issue by alexzayphing** [stravo1/obsidian-gdrive-sync#37]
I`m extremely interested on the plugin and would love to try it and provide feedback on discord.

But there's one thing bugging me out, will Obisidan **ever** allow this? I mean, it's a direct competitor to it's obsidian Sync

**Comment by stravo1** [comment]
this is the link to the discord server:
https://discord.com/invite/dPasX4Ac2P

and about will Obsidian allow it on their official plug-in list or will they take it down? im not sure, there are other similar back-up plug-ins already there on the plug-in list so this might be allowed, however this one, in my experience, is the most "plug-n-play" compared to others, so im not sure... even if they don't allow it on the official plug-in list, it's fine for me.

Obsidian Sync will almost always be better than what I as a solo dev can come up with, it will be more efficient for large vaults, more reliable, stable and just better. So in that sense they will always have an upper hand.
