### ISSUE TITLE
Got a "failed to load plugin"

### ISSUE THREAD

**Issue by Isaac-rise** [stravo1/obsidian-gdrive-sync#40]
I did every thing after the instructions. I even created a new vault and tried it again from beginning, it always appearing the same message.

**Comment by stravo1** [comment]
can you share screenshots? we also have a discord server for further discussing issues, please find the link in the README in the Support section.

thnaks :)

**Comment by Isaac-rise** [comment]
downloaded the wrong file

**Comment by stravo1** [comment]
mistakenly downloaded the source code zip, happens to the best of us 🫂
