### ISSUE TITLE
[Feature Request (kinda)] remove notifications at the bottom.

### ISSUE THREAD

**Issue by Geoxxer** [stravo1/obsidian-gdrive-sync#41]
I have enjoyed using this plugin and testing it. It would be great if the notifications you get at the bottom didn't show up that say like "file has been modified externally. Updating file changes" or something like that because it can be distracting while typing. Not sure if you have control over that.

**Comment by stravo1** [comment]
unfortunately no, you can type faster or increase the refresh time interval in settings to reduce the frequency of that pop-up, but you can't completely remove it :(
