### ISSUE TITLE
Updated files don't download

### ISSUE THREAD

**Issue by Strychnine22** [stravo1/obsidian-gdrive-sync#42]
At first, thank you for really amazing plugin :) It works really good at all, and I use it to sync my pc with android.
Plugin syncs new created/deleted files automatically really well, but doesn't auto download notes that were updated from other device (same version on both android and PC, 0.9.9-beta-14, manual files update and auto update newly created files works fine on both).

I saw similar issue opened on previous versions (#21), but it still doesn't work on newer versions of plugin.

Anyway, plugin works nice for me even without auto-updates.

UPD: I tried disabling all other plugins I had just in case, opened note still doesn't update automatically

**Comment by stravo1** [comment]
sorry, i didn't fully understand the issue. you mean to say if you edit a note in one device then the updated content doesn't appear on other devices?

**Comment by Strychnine22** [comment]
Yes, when I edit note in one device, it doesn't automatically update on other (even with note opened on other device)

**Comment by stravo1** [comment]
when you edit the note on one device, does the "lastSync" tag/property change on that device? also i would suggest using only one device at a time, it is preferable that you do not open the same not on two devices at the same time, might lead to race conditions

**Comment by Strychnine22** [comment]
Yes, lastSync tag changes, and I don't have issues with manually downloading/updating notes in obsidian. It doesn't sync automatically even when I edit note on phone, turn it off and open that note on PC

**Comment by stravo1** [comment]
i have found out the bug, please try beta-13, it is an issue with the latest release

**Comment by stravo1** [comment]
should be fixed at https://github.com/stravo1/obsidian-gdrive-sync/releases/tag/v0.9.9-beta-15

please try and report any issues, thanks for pointing this out :)

**Comment by Strychnine22** [comment]
Thank you so much! Fixed for me!
