### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'json')

### ISSUE THREAD

**Issue by jimmyc99** [stravo1/obsidian-gdrive-sync#47]
Tue Sep 24 2024 07:29:13 GMT+0300 (GMT+03:00)-Error-ERROR: Unable to complete action: - renameFile => TypeError - Cannot read properties of undefined (reading 'json') - TypeError: Cannot read properties of undefined (reading 'json')

[error-log-gdrive-plugin.md](https://github.com/user-attachments/files/17108008/error-log-gdrive-plugin.md)
[verbose-log-gdrive-plugin.md](https://github.com/user-attachments/files/17108009/verbose-log-gdrive-plugin.md)

**Comment by stravo1** [comment]
it's hard to guess the issue just from the logs, if there is a file named "pendingSync-gdrive-plugin" in your vault, you can try deleting that file and reopening the vault. keep a backup if all the notes please.

**Comment by jimmyc99** [comment]
That seems to have worked. Many thanks.
I guess the 'pending' file had become corrupted somehow.
Thanks again.

**Comment by stravo1** [comment]
if for some reason the pendingSync file got uploaded to Drive as well try deleting it from there (even from Bin).

**Comment by jimmyc99** [comment]
That seems to have solved it.
Many thanks.
