### ISSUE TITLE
Automatic sync toggle

### ISSUE THREAD

**Issue by selmali11** [stravo1/obsidian-gdrive-sync#49]
First of all, thank you very much for this plugin. I am trying to enable automatic sync using the latest release, but I do not see that option in the settings (see below). When I add a new file, I have to hit the initial upload again, which overwrites the files in my Google Drive and kind of defies the point of auto-sync

![image](https://github.com/user-attachments/assets/1fa979f1-f5fb-438f-80a4-9bb702c12a8c)

**Comment by stravo1** [comment]
there is no toggle, it auto syncs by default, you do NOT need to manually upload or download the files, they are uploaded and downloaded automatically. you can check for the "lastSync" tag on the notes whether they update as you edit them or not. and then you can open the vault with the same name and the plugin installed and logged in on another device and the updated note should be downloaded automatically.

**Comment by selmali11** [comment]
I actually do not see any "lastSync" tag. I see it defined in the main.js of the plugin but nothing on my notes. Properties in the document is set to visible. I am using the desktop version only

**Comment by stravo1** [comment]
seems like you did not initialize the vault as i can see in the screenshot, please click on initialize vault.
