### ISSUE TITLE
Deletting all my files

### ISSUE THREAD

**Issue by BERHAULTAurelien** [stravo1/obsidian-gdrive-sync#51]
Hello, i am very mad because this plugin was woring at the start but it started deleting all my files and spetialy erasing them when i create a table so i have lost aprox 5h of works so thx but no 

(ps : i am on win and IOS)

**Comment by stravo1** [comment]
all your deleted files are stored under the .trash directory in the vault location

**Comment by BERHAULTAurelien** [comment]
yes but as soon as i push the files it delete them anyway

**Comment by stravo1** [comment]
remove the lastSync tags from the files before putting them back.
