### ISSUE TITLE
CSS file breaks calendar plugin

### ISSUE THREAD

**Issue by SherlockH0** [stravo1/obsidian-gdrive-sync#52]
After I installed this plugin, Calendar's layout broke:
![1728395989 screensht](https://github.com/user-attachments/assets/a80481cb-1afc-4062-95d1-07e8ba848929)

It seems like `.container` class from Your plugin's CSS breaks other plugin's layout. After I commented out the whole styles file, Calendar got back to normal.

**Comment by stravo1** [comment]
thanks! will update the css class :))

**Comment by stravo1** [comment]
fixed https://github.com/stravo1/obsidian-gdrive-sync/releases/tag/v0.9.9-beta-16
