### ISSUE TITLE
Plugin breaks in v1.7

### ISSUE THREAD

**Issue by mahfy3w** [stravo1/obsidian-gdrive-sync#55]
Obsidian pushed some new changes in v1.7 that affects plugins, and it breaks this one. Enabling verbose logging doesn't do anything, so I can't see what went wrong. Uploading all files from the plugin's menu successfully initializes the vault in GDrive, but automatic uploading and individually uploading from the command palette doesn't update it in the Drive. The properties section of the files are in turn also unable to be updated.

**Comment by mahfy3w** [comment]
False alarm, somehow got it to work again

**Comment by stravo1** [comment]
it is not a false alarm, obsidian has probably disallowed file access while it is on the startup screen, we can disable the plugin on the loading screen and once inside the vault we can re-enable the plugin and everything works fine. working on a fix

**Comment by stravo1** [comment]
This is the breaking problem, code that runs at startup now needs to be wrapped in another onLayoutReady function:[Obsidian Docs](https://docs.obsidian.md/Plugins/Guides/Optimizing+plugin+load+time#If+you+have+code+that+you+want+to+run+at+startup%2C+where+should+it+go%3F)

**Comment by stravo1** [comment]
this issue is now fixed on beta-17, no user intervention required.

**Comment by xlfah** [comment]
@stravo1, I already update to beta-17 and still a big loading.

**Comment by stravo1** [comment]
@xlfah i too am on Obsidian 1.7.4. if possible please do join the discord server to help me debug this further.

**Comment by stravo1** [comment]
also is it showing that this plugin is having a slow load? might be due to other plugins as well.
