### ISSUE TITLE
Gdrive giving fatal error on boot

### ISSUE THREAD

**Issue by master-of-the-deck** [stravo1/obsidian-gdrive-sync#58]
[error-log-gdrive-plugin.md](https://github.com/user-attachments/files/17484758/error-log-gdrive-plugin.md)
[verbose-log-gdrive-plugin.md](https://github.com/user-attachments/files/17484759/verbose-log-gdrive-plugin.md)
I have been experiencing slow startups and crashes from the this plugin consistently on both PC (Windows 10) and Android (Samsung Galaxy A54 5G, running Android v14). I have Obsidian v1.7.4 and Google Drive Sync version 0.9.9-beta-13-1. The other community plugin I use is Smart Typography. I use a number of core plugins in addition (but it's a long list so I figured I would provide it only if relevant).

I have tried disabling + re-enabling the plugin, which doesn't resolve the issue. It happens consistently on startup for Android and Windows PC.

(I am not experienced with software, please let me know if additional information would be helpful.)

**Comment by stravo1** [comment]
https://github.com/stravo1/obsidian-gdrive-sync/issues/55

please update the plugin to the latest release.

plugin before beta-17 breaks in Obsidian v1.7, consider joining the discord server to receive updates. if not please keep an eye on the releases page to look for updates. a lot of major bigs have been fixed since beta-13.

**Comment by stravo1** [comment]
also please backup everything before you update.

**Comment by master-of-the-deck** [comment]
Will do. I've been using the native update checker in Obsidian to check for updates; should I be looking elsewhere? It still says I don't have any updates (which is why I've seemingly gotten so behind on updates)

**Comment by stravo1** [comment]
yes so this plugin is not on the official list of plugins so you won't be getting native updates.

to update the plugin first close obsidian, then download the "main.js" and "manifest.json" and "styles.css" files from the latest release and replace the old ones under the vault/.obsidian/plugins/obsidian-gdrive-sync

or you can create a copy/backup of the "data.json" file under the plugin folder and the download the zip from the latest release as you did when you first installed the plugin, extract it and replace the old obsidian-gdrive-sync folder with the new one. this would mean that you will lose your plugin settings though. place the backed up "data.json" in the new folder to restore the plugin settings.

**Comment by master-of-the-deck** [comment]
Re-reading your post when I was not half-asleep clarified what you meant haha. I have updated my Android and desktop apps and everything works fine now! Thanks for all your help and I'm sorry for bothering you with such a trivial mistake on my end! I'll try to keep up better with the updates in the future.

**Comment by stravo1** [comment]
no worries :)
