### ISSUE TITLE
"NoteName.md" Has been modified externally, merging changes automatically is very annoying

### ISSUE THREAD

**Issue by RizzlerBros** [stravo1/obsidian-gdrive-sync#60]
everytime this notification appears, i need to refocus my text cursos, this makes typing disrupted
![Screenshot 2024-10-25 025039](https://github.com/user-attachments/assets/62f44173-d760-4cad-962c-3ecf3b5aae4f)

any idea how to fix this?

**Comment by stravo1** [comment]
duplicate of #45
