### ISSUE TITLE
gsync takes too long to load, crash, not uploading

### ISSUE THREAD

**Issue by TheMcKingX** [stravo1/obsidian-gdrive-sync#62]
Gsync was working fine but now it crashes when starting on desktop or android.
[error-log-gdrive-plugin.md](https://github.com/user-attachments/files/17703977/error-log-gdrive-plugin.md)
[verbose-log-gdrive-plugin.md](https://github.com/user-attachments/files/17703978/verbose-log-gdrive-plugin.md)
![osbdiain error](https://github.com/user-attachments/assets/31576b93-5a52-4f6b-80b1-dac1d4e642f3)

**Comment by stravo1** [comment]
are you on beta-17? if not please refer #55

**Comment by TheMcKingX** [comment]
that was it. thank you.
