### ISSUE TITLE
Sync Issue - renameFile => TypeError

### ISSUE THREAD

**Issue by JurPer** [stravo1/obsidian-gdrive-sync#65]
Hey,
I'm suddenly having problems with the sync. The error log says "renameFile => TypeError - Cannot read properties of undefined".
How can I find out which file(s) are the problem?

[error-log-gdrive-plugin.md](https://github.com/user-attachments/files/17804746/error-log-gdrive-plugin.md)

**Comment by stravo1** [comment]
closing the issue assuming it was solved?
