### ISSUE TITLE
so good !!! thank you. and question on updates 

### ISSUE THREAD

**Issue by avichou** [stravo1/obsidian-gdrive-sync#8]
god bless you man, sorry to open an issue for it but you're truly awesome :))

few questions; does it sync everything including the plugins? and how do we update it , are we notified of new updates , or do we have to manually check in github ?

**Comment by stravo1** [comment]
no, the plugin has access to only the files in the vault and not in the `.obsidian` folder where all other plugins and their settings are stored. so it can only sync notes and attachments, not plugins.

and as of right now, it's not on the official plug-in list so keeping an eye on the releases on GitHub is the only option to update the plug-in. you can "Watch" the repo to get notified of any updates.

while updating the plugin you have to replace all the three files with the files from the latest release (main.js, styles.css and manifest.json) but you can keep the data.json file which stores the plug-in settings, so you won't be logged out.

**Comment by stravo1** [comment]
https://github.com/stravo1/obsidian-gdrive-sync/issues/4#issuecomment-1920461080

**Comment by avichou** [comment]
> no, the plugin has access to only the files in the vault and not in the `.obsidian` folder where all other plugins and their settings are stored. so it can only sync notes and attachments, not plugins.
> 
> and as of right now, it's not on the official plug-in list so keeping an eye on the releases on GitHub is the only option to update the plug-in. you can "Watch" the repo to get notified of any updates.
> 
> while updating the plugin you have to replace all the three files with the files from the latest release (main.js, styles.css and manifest.json) but you can keep the data.json file which stores the plug-in settings, so you won't be logged out.

thank you. is it problematic to update phone and desktop plugin at a different time ? 

like using plugin v2 on desktop, while phone is still on plugin v1 ?

**Comment by stravo1** [comment]
> > no, the plugin has access to only the files in the vault and not in the `.obsidian` folder where all other plugins and their settings are stored. so it can only sync notes and attachments, not plugins.
> > and as of right now, it's not on the official plug-in list so keeping an eye on the releases on GitHub is the only option to update the plug-in. you can "Watch" the repo to get notified of any updates.
> > while updating the plugin you have to replace all the three files with the files from the latest release (main.js, styles.css and manifest.json) but you can keep the data.json file which stores the plug-in settings, so you won't be logged out.
> 
> thank you. is it problematic to update phone and desktop plugin at a different time ?
> 
> like using plugin v2 on desktop, while phone is still on plugin v1 ?

it should not be an issue unless there are breaking/major structural changes.
