### ISSUE TITLE
adds "lastsync: Fri Mar 29 2024 03:48:32 GMT+0100 " after every note, and crash bug in comments 

### ISSUE THREAD

**Issue by avichou** [stravo1/obsidian-gdrive-sync#9]
<img width="355" alt="image" src="https://github.com/stravo1/obsidian-gdrive-sync/assets/86660671/fd6b600a-3e9e-4980-a758-1ab54c20b24f">

![Screenshot_20240329_034456_Obsidian](https://github.com/stravo1/obsidian-gdrive-sync/assets/86660671/06902af3-4761-49c6-b7f4-4243af95c743)

https://github.com/stravo1/obsidian-gdrive-sync/assets/86660671/89cc1eca-bf76-4695-ae32-20827532a706

**Comment by stravo1** [comment]
The plug-in tracks the last synced time using a meta tag that it appends to the starting of each file, it should look like this:

![Screenshot_20240329-083123.png](https://github.com/stravo1/obsidian-gdrive-sync/assets/76593476/8f01c711-8f89-4b5c-979d-780dc271a427)

Please don't edit that tag. Will add this info to the README file.
I would request you to turn off the plug-in, delete the 
`
---
lastSync: ...
---
`
part from the notes where instead of being under "Properties" as shown in the screenshot it appears as a heading.

If issue persists, enable "Verbose Logging" and "Error Logging" and upload the logs here.

**Comment by avichou** [comment]
> The plug-in tracks the last synced time using a meta tag that it appends to the starting of each file, it should look like this:
> 
> ![Screenshot_20240329-083123.png](https://private-user-images.githubusercontent.com/76593476/317941721-8f01c711-8f89-4b5c-979d-780dc271a427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODIwMjAsIm5iZiI6MTcxMTY4MTcyMCwicGF0aCI6Ii83NjU5MzQ3Ni8zMTc5NDE3MjEtOGYwMWM3MTEtOGY4OS00YjVjLTk3OWQtNzgwZGMyNzFhNDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAzMDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYjRmZjdhNjdkZDc2M2E4NTRlNjMxMGFiMDRjZjFhMTQ4OWRkZTQ3ODVhNmFmMjU5ZWVjN2FkYjNkMGQ2YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O9gokAedw4gCs5-pIn9nHigm6NBbrEoBM7W2hjQ463U)
> 
> Please don't edit that tag. Will add this info to the README file. I would request you to turn off the plug-in, delete the
> 
> ```
> ---
> lastSync: ...
> ---
> ```
> 
> part from the notes where instead of being under "Properties" as shown in the screenshot it appears as a heading.
> 
> If issue persists, enable "Verbose Logging" and "Error Logging" and upload the logs here.

oh damn thanks 

hmm the issue is that for me it shows up IN the note , why doesn't it behave like this for you ? 

okay EDIT: i've just tried adding a new note and it seems i need to wait a bit for "properties to work", otherwise if i go into the note's body too fast, properties (last sync and date) get addded to the body of the note ! thought that might help you :)

**Comment by stravo1** [comment]
ahh got it, there's probably some race conditions being introduced, i couldn't replicate it on my device, if you can provide me with the steps to reproduce the issue (it'll be best if you can provide a screen recording). but thanks for pointing it out, will add it to the FAQ section in the README file.

**Comment by avichou** [comment]
> ahh got it, there's probably some race conditions being introduced, i couldn't replicate it on my device, if you can provide me with the steps to reproduce the issue (it'll be best if you can provide a screen recording). but thanks for pointing it out, will add it to the FAQ section in the README file.

I am currently unable to reproduce the issue again, if i manage to do it in the future i'll ping you 

btw, is there a way within obsidian to simply not show property (or even better, this property in particular) ? for a cleaner look

like IDK how I did it, but now my phone doesnt show it (still syncs perfectly though), but my mac does 

<img width="401" alt="image" src="https://github.com/stravo1/obsidian-gdrive-sync/assets/86660671/dca14f1b-e793-4bf2-8188-25a923a50a41">

<img width="401" alt="image" src="https://github.com/stravo1/obsidian-gdrive-sync/assets/86660671/6462f9f0-1e23-499b-9a0b-de5f6a9b88bc">

**Comment by stravo1** [comment]
![Screenshot_20240331-092450.png](https://github.com/stravo1/obsidian-gdrive-sync/assets/76593476/65560f0b-c996-4330-b1cc-1086c591d8ac)

this is how you did it on your mobile, not sure if this setting is exclusive to the mobile version, i bet it's not.
